spring:
  datasource:
    url: jdbc:mysql://test.cspipudysx5o.us-east-2.rds.amazonaws.com:3306/rwws_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: rwweb
    password: RwWeb2023