spring:
  datasource:
    url: jdbc:mysql://rw-test-website-01.cspipudysx5o.us-east-2.rds.amazonaws.com:3306/rwws_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: rwweb
    password: RwWeb2023
  mail:
    host: smtp.163.com
    port: 465
    username: beiding92@163.com
    password: KWLRIHTLERXQVDTI
    code:
      expiration: 120
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: rw-admin-secret #JWT加解密使用的密钥
  expiration: 18000 #JWT的超期限时间(60*60*5)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
# redis 连接池配置信息
redis:
  database: 1
  host: 127.0.0.1
  lettuce:
    pool:
      max-active: 100
      min-idle: 10
      max-idle: 10
      max-wait: 30000ms
  port: 6379
  timeout: 10000ms
  password:
thread:
  core-pool-size: 4
  queue-capacity: 1000
