spring:
  datasource:
    url: jdbc:mysql://rw-test-website-01.cspipudysx5o.us-east-2.rds.amazonaws.com:3306/rwws_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: rwweb
    password: RwWeb2023
  liquibase:
    change-log: classpath:db/master.xml
    database-change-log-table: rw_databasechangelog
    database-change-log-lock-table: rw_databasechangeloglock
mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: assign_id
springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
    csrf:
      enabled: true
    disable-swagger-default-url: true
application:
  super-admin-password: Z2D%GP#$Z8b%@KEm
  remember-me-key: CNpNhLLkeAvjkaJLZm6BTFvegLRvbdkzud4dUv2LvjFfEmCuzK2RjH22eBnY9Vwpjb2gDcvNSfMQ3Em4CB4Ykhg5TAcxCXncW9y
