spring:
  datasource:
    url: jdbc:mysql://rw-test-website-01.cspipudysx5o.us-east-2.rds.amazonaws.com:3306/rwws_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: rwweb
    password: RwWeb2023
  redis:
    database: 1
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 100
        min-idle: 10
        max-idle: 10
        max-wait: 30000ms
    port: 6379
    password:
    timeout: 10000ms
jwt:
  secret: rw-admin-secret #JWT加解密使用的密钥
  expiration:
    duration: 1
    unit: DAYS
thread:
  core-pool-size: 4
  queue-capacity: 1000
