spring:
  datasource:
    url: jdbc:mysql://rw-test-website-01.cspipudysx5o.us-east-2.rds.amazonaws.com:3306/rwws_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: rwweb
    password: RwWeb2023
  liquibase:
    change-log: classpath:db/master.xml
    database-change-log-table: rw_databasechangelog
    database-change-log-lock-table: rw_databasechangeloglock
mybatis-plus:
  global-config:
    banner: false
