spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rwws_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Lcjq3r-aQB
  mail:
    host: smtp.163.com
    username: beiding92@163.com
    password: KWLRIHTLERXQVDTI
  redis:
    database: 1
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 100
        min-idle: 10
        max-idle: 10
        max-wait: 30000ms
    port: 6379
    password:
    timeout: 10000ms
  liquibase:
    enabled: true
jwt:
  secret: rw-admin-secret #JWT加解密使用的密钥
  expiration:
    duration: 1
    unit: DAYS
thread:
  core-pool-size: 4
  queue-capacity: 1000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
